"""
Tests for ExportPackingListService (app/services.py) - the EXPORT PACKING
LIST that accompanies an Export Invoice. It is never created directly, so
every test here goes through ExportInvoiceService.create/update, which is
the only thing that generates one.

The three behaviours worth pinning down are the ones the document exists
for:

  - it is generated BY DEFAULT (saving an invoice always yields a printable
    packing list, even with no split typed in),
  - the split BALANCES (per goods line, boxes across containers add up to
    exactly the invoice's boxes - no box loaded twice, none left behind),
  - the printed rows GROUP BY HSN automatically (rows re-ordered so a group
    runs together, one heading per run, carried across containers).
"""

import pytest

from app.exceptions import ValidationError


CONTAINERS = [
    {"container_no": "BLJU2253726", "line_seal_no": "UFL331090", "rfid_seal_no": "WIND02432727", "vehicle_no": ""},
    {"container_no": "SEGU3227471", "line_seal_no": "UFL331095", "rfid_seal_no": "WIND02531142", "vehicle_no": ""},
]


def make_product(container, seed, name, hsn, category_id=None, alt_qty="1.44", net=26.5, gross=27.0):
    return container.product_service.create_product(
        current_user=seed.admin, product_name=name, description="", hsn_code=hsn,
        igst_percent="18", quantity="4", alternate_quantity=alt_qty,
        category_id=category_id, net_weight_kg=net, gross_weight_kg=gross,
    )


def item_for(product, boxes, pallets=None, price="5.92", pallet_weight_kg=None):
    return {
        "product_id": str(product.id), "product_name": product.product_name,
        "hsn_code": product.hsn_code, "quantity_boxes": str(boxes),
        "quantity_value": "0", "unit": "SQM", "price_usd": price,
        "pallets": "" if pallets is None else str(pallets),
        "pallet_weight_kg": "" if pallet_weight_kg is None else str(pallet_weight_kg),
    }


def make_export(container, seed, raw_items, allocations=None, containers=None, number="1000000001", **over):
    fields = {
        "consignee_name": "ROBUST INTERNATIONAL", "invoice_date": "2026-02-20",
        "tax_mode": "igst", "exchange_rate": "86.70", "export_invoice_number": number,
        "container_details_list": CONTAINERS if containers is None else containers,
    }
    if allocations is not None:
        fields["packing_allocations"] = allocations
    fields.update(over)
    return container.export_invoice_service.create(seed.admin, fields, raw_items)


def packing_list_for(container, seed, invoice):
    return container.export_packing_list_service.get_for_invoice(invoice.id, seed.company_id)


def alloc(container_index, item_index, boxes, **over):
    row = {"container_index": str(container_index), "invoice_item_index": str(item_index),
           "quantity_boxes": str(boxes)}
    row.update(over)
    return row


# ==========================================================================
# Generated by default
# ==========================================================================
class TestGeneratedByDefault:
    def test_saving_an_invoice_generates_a_packing_list(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100")
        invoice = make_export(container, seed, [item_for(product, 100)])

        packing_list = packing_list_for(container, seed, invoice)
        assert packing_list is not None
        assert packing_list.export_invoice_id == invoice.id
        assert packing_list.packing_list_number.startswith("EXPPL20260220")

    def test_with_no_split_typed_in_everything_lands_in_container_one(self, container, seed):
        a = make_product(container, seed, "GVT 600X1200", "69072100")
        b = make_product(container, seed, "ADHESIVE", "38245090")
        invoice = make_export(container, seed, [item_for(a, 100), item_for(b, 40)])

        packing_list = packing_list_for(container, seed, invoice)
        assert [i.quantity_boxes for i in packing_list.items] == [100, 40]
        assert {i.container_sr_no for i in packing_list.items} == {1}
        assert [i.container_no for i in packing_list.items] == ["BLJU2253726", "BLJU2253726"]

    def test_the_number_survives_later_edits_of_the_invoice(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100")
        invoice = make_export(container, seed, [item_for(product, 100)])
        first_number = packing_list_for(container, seed, invoice).packing_list_number

        container.export_invoice_service.update(
            seed.admin, invoice.id,
            {"consignee_name": "ROBUST INTERNATIONAL", "invoice_date": "2026-03-01",
             "export_invoice_number": "1000000001", "tax_mode": "igst", "exchange_rate": "86.70",
             "container_details_list": CONTAINERS},
            [item_for(product, 100)],
        )
        after = packing_list_for(container, seed, invoice)
        assert after.packing_list_number == first_number

    def test_deleting_the_invoice_takes_the_packing_list_with_it(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100")
        invoice = make_export(container, seed, [item_for(product, 100)])
        assert packing_list_for(container, seed, invoice) is not None

        container.export_invoice_service.delete(seed.admin, invoice.id)
        assert packing_list_for(container, seed, invoice) is None


# ==========================================================================
# The balance: no box double-loaded, none left behind
# ==========================================================================
class TestBoxBalance:
    def test_a_line_can_be_split_across_containers(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100")
        invoice = make_export(
            container, seed, [item_for(product, 100)],
            allocations=[alloc(0, 0, 60), alloc(1, 0, 40)],
        )
        packing_list = packing_list_for(container, seed, invoice)
        assert [(i.container_sr_no, i.quantity_boxes) for i in packing_list.items] == [(1, 60), (2, 40)]

    def test_over_allocating_is_refused(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100")
        with pytest.raises(ValidationError) as e:
            make_export(container, seed, [item_for(product, 100)],
                        allocations=[alloc(0, 0, 60), alloc(1, 0, 50)])
        assert "only has 100" in str(e.value)

    def test_under_allocating_is_refused(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100")
        with pytest.raises(ValidationError) as e:
            make_export(container, seed, [item_for(product, 100)],
                        allocations=[alloc(0, 0, 60), alloc(1, 0, 30)])
        assert "still unassigned" in str(e.value)

    def test_a_line_left_out_of_the_split_entirely_is_refused(self, container, seed):
        a = make_product(container, seed, "GVT 600X1200", "69072100")
        b = make_product(container, seed, "ADHESIVE", "38245090")
        with pytest.raises(ValidationError) as e:
            make_export(container, seed, [item_for(a, 100), item_for(b, 40)],
                        allocations=[alloc(0, 0, 100)])
        assert "ADHESIVE" in str(e.value)

    def test_a_rejected_split_leaves_no_invoice_behind(self, container, seed):
        """The split is validated before anything is written, so a bad one
        must not half-save the export invoice it came in with."""
        product = make_product(container, seed, "GVT 600X1200", "69072100")
        with pytest.raises(ValidationError):
            make_export(container, seed, [item_for(product, 100)],
                        allocations=[alloc(0, 0, 999)], number="1000000009")
        assert container.export_invoice_service.list_all(seed.company_id) == []

    def test_a_line_without_a_box_count_cannot_be_split(self, container, seed):
        product = make_product(container, seed, "SANITARYWARE", "69072100")
        boxless = item_for(product, 0)
        boxless["quantity_boxes"] = ""
        boxless["quantity_value"] = "25"
        with pytest.raises(ValidationError) as e:
            make_export(container, seed, [boxless], allocations=[alloc(0, 0, 10), alloc(1, 0, 15)])
        assert "no box count" in str(e.value)

    def test_a_blank_product_row_does_not_shift_the_split(self, container, seed):
        """_build_items drops rows with no product name, so the form's row
        indexes and the built goods lines don't line up 1:1 - the split has
        to be remapped or it silently attaches to the wrong product."""
        a = make_product(container, seed, "GVT 600X1200", "69072100")
        b = make_product(container, seed, "ADHESIVE", "38245090")
        blank = {"product_name": "", "quantity_value": "", "price_usd": "", "quantity_boxes": ""}
        invoice = make_export(
            container, seed, [item_for(a, 100), blank, item_for(b, 40)],
            allocations=[alloc(0, 0, 100), alloc(1, 2, 40)],
        )
        packing_list = packing_list_for(container, seed, invoice)
        assert {(i.product_name, i.quantity_boxes) for i in packing_list.items} == {
            ("GVT 600X1200", 100), ("ADHESIVE", 40),
        }


# ==========================================================================
# Derived quantities
# ==========================================================================
class TestDerivedFigures:
    def test_quantity_and_pallets_are_pro_rata_and_add_back_up(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100", alt_qty="1.44")
        invoice = make_export(
            container, seed, [item_for(product, 100, pallets=20)],
            allocations=[alloc(0, 0, 60), alloc(1, 0, 40)],
        )
        packing_list = packing_list_for(container, seed, invoice)
        # The invoice line is 100 boxes x 1.44 SQM = 144 SQM on 20 pallets.
        assert [i.quantity_value for i in packing_list.items] == [86.4, 57.6]
        assert [i.pallets for i in packing_list.items] == [12, 8]
        assert packing_list.total_quantity == pytest.approx(144)
        assert packing_list.total_pallets == pytest.approx(20)

    def test_weights_come_from_the_catalog_products_per_box_figures(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100", net=26.5, gross=27.0)
        invoice = make_export(container, seed, [item_for(product, 100)],
                              allocations=[alloc(0, 0, 100)])
        packing_list = packing_list_for(container, seed, invoice)
        assert packing_list.total_net_weight == pytest.approx(2650)
        assert packing_list.total_gross_weight == pytest.approx(2700)

    def test_a_typed_weight_overrides_the_derived_one(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100", net=26.5, gross=27.0)
        invoice = make_export(
            container, seed, [item_for(product, 100)],
            allocations=[alloc(0, 0, 100, net_weight_kg="2400", gross_weight_kg="2480")],
        )
        packing_list = packing_list_for(container, seed, invoice)
        assert packing_list.total_net_weight == pytest.approx(2400)
        assert packing_list.total_gross_weight == pytest.approx(2480)

    def test_gross_weight_is_net_plus_pallets_times_pallet_type_weight_once_a_type_is_selected(self, container, seed):
        # A named pallet type (its own weight, snapshotted the moment it's
        # picked on the goods line - ExportInvoiceItem.pallet_weight_kg)
        # replaces the flat per-box gross formula: Net = 100 boxes x 26.5 =
        # 2650, plus 20 pallets x 22.5 kg/pallet = 450, so Gross = 3100 - NOT
        # 100 x the product's own per-box gross weight (2700).
        product = make_product(container, seed, "GVT 600X1200", "69072100", net=26.5, gross=27.0)
        invoice = make_export(
            container, seed, [item_for(product, 100, pallets=20, pallet_weight_kg=22.5)],
            allocations=[alloc(0, 0, 100)],
        )
        packing_list = packing_list_for(container, seed, invoice)
        assert packing_list.total_net_weight == pytest.approx(2650)
        assert packing_list.total_gross_weight == pytest.approx(3100)

    def test_pallet_type_weight_formula_splits_correctly_across_containers(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100", net=26.5, gross=27.0)
        invoice = make_export(
            container, seed, [item_for(product, 100, pallets=20, pallet_weight_kg=22.5)],
            allocations=[alloc(0, 0, 60), alloc(1, 0, 40)],
        )
        packing_list = packing_list_for(container, seed, invoice)
        # 60 boxes -> net 1590, 12 pallets (pro-rata) x 22.5 = 270 -> gross 1860.
        # 40 boxes -> net 1060, 8 pallets x 22.5 = 180 -> gross 1240.
        nets = [i.net_weight_kg for i in packing_list.items]
        grosses = [i.gross_weight_kg for i in packing_list.items]
        assert nets == pytest.approx([1590, 1060])
        assert grosses == pytest.approx([1860, 1240])
        assert packing_list.total_gross_weight == pytest.approx(3100)

    def test_a_typed_gross_override_wins_over_the_pallet_weight_formula(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100", net=26.5, gross=27.0)
        invoice = make_export(
            container, seed, [item_for(product, 100, pallets=20, pallet_weight_kg=22.5)],
            allocations=[alloc(0, 0, 100, gross_weight_kg="2999")],
        )
        packing_list = packing_list_for(container, seed, invoice)
        assert packing_list.total_gross_weight == pytest.approx(2999)

    def test_no_pallet_type_falls_back_to_the_products_per_box_gross_weight(self, container, seed):
        # No pallet type known for this line (Loose, or Plts typed by hand
        # with no type picked) - pallets is set but pallet_weight_kg isn't,
        # so Gross falls back to the old Boxes x per-box formula.
        product = make_product(container, seed, "GVT 600X1200", "69072100", net=26.5, gross=27.0)
        invoice = make_export(
            container, seed, [item_for(product, 100, pallets=20)],
            allocations=[alloc(0, 0, 100)],
        )
        packing_list = packing_list_for(container, seed, invoice)
        assert packing_list.total_gross_weight == pytest.approx(2700)

    def test_container_identity_is_snapshotted_from_section_11b(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100")
        invoice = make_export(container, seed, [item_for(product, 100)],
                              allocations=[alloc(1, 0, 100)])
        item = packing_list_for(container, seed, invoice).items[0]
        assert (item.container_no, item.seal_no, item.rfid_seal_no) == (
            "SEGU3227471", "UFL331095", "WIND02531142",
        )

    def test_container_totals_sum_per_container_for_the_export_invoices_11b_table(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100", alt_qty="1.44", net=26.5, gross=27.0)
        invoice = make_export(
            container, seed, [item_for(product, 100, pallets=20)],
            allocations=[alloc(0, 0, 60), alloc(1, 0, 40)],
        )
        totals = packing_list_for(container, seed, invoice).container_totals
        # container 1 (index 0 -> sr_no 1): 60 boxes, 12 plts, 60*26.5/27.0 KG
        assert totals[1]["quantity_boxes"] == pytest.approx(60)
        assert totals[1]["pallets"] == pytest.approx(12)
        assert totals[1]["net_weight_kg"] == pytest.approx(1590)
        assert totals[1]["gross_weight_kg"] == pytest.approx(1620)
        # container 2 (index 1 -> sr_no 2): 40 boxes, 8 plts, 40*26.5/27.0 KG
        assert totals[2]["quantity_boxes"] == pytest.approx(40)
        assert totals[2]["pallets"] == pytest.approx(8)
        assert totals[2]["net_weight_kg"] == pytest.approx(1060)
        assert totals[2]["gross_weight_kg"] == pytest.approx(1080)


# ==========================================================================
# Automatic HSN grouping
# ==========================================================================
class TestHsnGrouping:
    def test_group_label_defaults_to_the_products_category(self, container, seed):
        category = container.product_service.create_category(seed.admin, "GLAZED VIRTIFIED TILES")
        product = make_product(container, seed, "GVT 600X1200", "69072100", category_id=category.id)
        invoice = make_export(container, seed, [item_for(product, 100)])
        item = packing_list_for(container, seed, invoice).items[0]
        assert item.group_label == "GLAZED VIRTIFIED TILES"

    def test_group_label_falls_back_to_the_product_name_without_a_category(self, container, seed):
        product = make_product(container, seed, "Tiles Adhesive", "38245090")
        invoice = make_export(container, seed, [item_for(product, 100)])
        assert packing_list_for(container, seed, invoice).items[0].group_label == "TILES ADHESIVE"

    def test_rows_keep_their_entered_order_within_a_container(self, container, seed):
        """Designs are no longer grouped or re-sorted by product/HSN - the
        sheet prints rows in the order they were allocated."""
        tiles = container.product_service.create_category(seed.admin, "TILES")
        a = make_product(container, seed, "GVT 600X1200", "69072100", category_id=tiles.id)
        glue = make_product(container, seed, "ADHESIVE", "38245090")
        b = make_product(container, seed, "GVT 300X600", "69072100", category_id=tiles.id)
        invoice = make_export(
            container, seed, [item_for(a, 10), item_for(glue, 20), item_for(b, 30)],
            allocations=[alloc(0, 0, 10), alloc(0, 1, 20), alloc(0, 2, 30)],
        )
        packing_list = packing_list_for(container, seed, invoice)
        assert [i.product_name for i in packing_list.items] == [
            "GVT 600X1200", "ADHESIVE", "GVT 300X600",
        ]
        rows = packing_list.printed_containers[0]["rows"]
        assert all(r["kind"] == "item" for r in rows)

    def test_containers_are_kept_in_order_but_not_re_grouped(self, container, seed):
        tiles = container.product_service.create_category(seed.admin, "TILES")
        a = make_product(container, seed, "GVT 600X1200", "69072100", category_id=tiles.id)
        glue = make_product(container, seed, "ADHESIVE", "38245090")
        invoice = make_export(
            container, seed, [item_for(a, 100), item_for(glue, 20)],
            allocations=[alloc(0, 0, 60), alloc(1, 1, 20), alloc(1, 0, 40)],
        )
        packing_list = packing_list_for(container, seed, invoice)
        printed = packing_list.printed_containers
        assert len(printed) == 2
        assert [r["item"].product_name for r in printed[1]["rows"]] == [
            "ADHESIVE", "GVT 600X1200",
        ]

    def test_container_cells_span_the_whole_run_of_rows(self, container, seed):
        tiles = container.product_service.create_category(seed.admin, "TILES")
        a = make_product(container, seed, "GVT 600X1200", "69072100", category_id=tiles.id)
        glue = make_product(container, seed, "ADHESIVE", "38245090")
        invoice = make_export(
            container, seed, [item_for(a, 10), item_for(glue, 20)],
            allocations=[alloc(0, 0, 10), alloc(0, 1, 20)],
        )
        printed = packing_list_for(container, seed, invoice).printed_containers
        assert printed[0]["rowspan"] == 2


# ==========================================================================
# Reads / tenant scoping
# ==========================================================================
class TestReads:
    def test_list_all_is_tenant_scoped(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100")
        make_export(container, seed, [item_for(product, 100)])
        other = container.tenant_repo.create("Other Co", "other")
        assert len(container.export_packing_list_service.list_all(seed.company_id)) == 1
        assert container.export_packing_list_service.list_all(other.id) == []

    def test_get_is_tenant_scoped(self, container, seed):
        from app.exceptions import NotFoundError
        product = make_product(container, seed, "GVT 600X1200", "69072100")
        invoice = make_export(container, seed, [item_for(product, 100)])
        packing_list = packing_list_for(container, seed, invoice)
        other = container.tenant_repo.create("Other Co", "other")
        with pytest.raises(NotFoundError):
            container.export_packing_list_service.get(packing_list.id, other.id)

    def test_the_parent_invoice_is_attached_for_the_printed_header(self, container, seed):
        product = make_product(container, seed, "GVT 600X1200", "69072100")
        invoice = make_export(container, seed, [item_for(product, 100)])
        got = container.export_packing_list_service.get(
            packing_list_for(container, seed, invoice).id, seed.company_id
        )
        assert got.invoice is not None
        assert got.invoice.export_invoice_number == invoice.export_invoice_number
